ALTER TABLE members ADD COLUMN IF NOT EXISTS street_address TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS village TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS barangay TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS city TEXT;
